### ISSUE TITLE
Add support to metadata

### ISSUE THREAD

**Issue by luisfmelo** [muesli/kmeans#10]
In certain cases, we want to apply the algorithm to get the clusters but, once we have the observations, we want other information associated with the observations of the clusters.

Imagine that we have a lot of circles. Each circle has a unique colour and a radius. We want to apply clustering by the radius. In the end, we want to check in which cluster is the green circle.

Is it possible?

**Comment by muesli** [comment]
This is already possible!

Note that `clusters.Observation` [1] is merely an interface, so you can implement (or wrap) your own types that fulfill it.

There's a nice example here, which uses this technique to map colors to coordinates:
https://github.com/muesli/kmeans/blob/master/examples/colorpalette/main.go

Let me know if that helps you!

[1]: https://github.com/muesli/clusters/blob/master/observations.go
