### ISSUE TITLE
Fix indirect dependency go-sdk

### ISSUE THREAD

**Issue by Baldomo** [muesli/kmeans#16]
Currently (6 dec 2020) this module cannot be imported in a Go 1.15.5 based project using modules because the `go-sdk` indirect dependency (which I was not able to find as a dependency of this module's dependencies) does not appear to have a `v2.0.0` version, making `go mod` and `go get` refuse to work properly, even when generting a new `go.mod` for my project ([paletter](https://github.com/Baldomo/paletter)), whith the following error:

```
go: github.com/muesli/kmeans@v0.2.0 requires
	github.com/blend/go-sdk@v2.0.0+incompatible: reading github.com/blend/go-sdk/go.mod at revision v2.0.0: unknown revision v2.0.0
```

As a sidenote, `go-chart` v2 as a module has to imported as `github.com/wcharczuk/go-chart/v2`

**Comment by muesli** [comment]
Should be fixed in v0.2.1.
