### ISSUE TITLE
Evaluation and assessment

### ISSUE THREAD

**Issue by vosmith** [muesli/kmeans#4]
Nice work on the kmeans implementation!  Do you plan on adding functions for evaluating the clusters?  Here is a wikipedia article that has some metrics that may be worth adding.

https://en.wikipedia.org/wiki/Cluster_analysis#Evaluation_and_assessment

**Comment by muesli** [comment]
That would be nice and certainly sounds intriguing, even though I would potentially consider that a different package / scope.

**Comment by vosmith** [comment]
Yes sir :+1:

**Comment by muesli** [comment]
@vosmith Do you have some experience with regard to this subject?

**Comment by muesli** [comment]
@vosmith Check out https://github.com/muesli/silhouette :) Hope this helps!

**Comment by vosmith** [comment]
Awesome this looks great!
