### ISSUE TITLE
K means doesn't build. Seems that dependency has changed API

### ISSUE THREAD

**Issue by evanoberholster** [muesli/kmeans#8]
# github.com/muesli/kmeans
../../../../muesli/kmeans/plotter.go:45:5: unknown field 'Show' in struct literal of type chart.Style
../../../../muesli/kmeans/plotter.go:58:4: unknown field 'Show' in struct literal of type chart.Style
../../../../muesli/kmeans/plotter.go:73:5: unknown field 'Show' in struct literal of type chart.Style
../../../../muesli/kmeans/plotter.go:78:5: unknown field 'Show' in struct literal of type chart.Style

**Comment by muesli** [comment]
I've just pushed a go.mod & go.sum, which should make it compile again, with Go 1.11+ and Go modules enabled.
